### ISSUE TITLE
Pull most downloaded

### ISSUE THREAD

**Issue by DeuX01** [Buried-In-Code/Mediux-Posters#3]
Hello!
First of all, let me tell you that I LOVE what you did with this script, it saves me so much time!
The issue is not an issue; it's more of a suggestion. Currently, it seems that the posters pulled are not the most downloaded. Maybe it's random what it pulls. So my suggestion, if possible of course, is to add a flag or even by default, to pull the set with most downloads.

Another suggestion would be to add a flag to pull only Title Cards if available.

Once again, thank you so much for this amazing tool.

**Comment by Buried-In-Code** [comment]
Currently it uses a list of hardcoded usernames, I eventually plan on allowing you to populate the list via the settings file. I could set it if the list is empty to use the most downloaded instead.

The hardcoded list currently is: "zardooohasselfrau", "jezzfreeman", "Tiederian", "willtong93", "MiniZaki", "RuviLev"

**Comment by Buried-In-Code** [comment]
Filtering to just be titlecards is a bit more difficult, I'll take a look and see if its possible

**Comment by DeuX01** [comment]
Awesome, I’ll play with it a bit tomorrow then. Thank you very much

**Comment by DeuX01** [comment]
Sorry to extend my requests, but I remember something that can be useful. Currently you exclude by type show or movie, what about adding excluding by library? Example, I have a library of Movies in German and I want those to stick to the German posters, but if I want to change the regular English posters there's no need to exclude the German movie library. Same for shows, if I want to keep the anime posters for example. Unless I miss something.

Thank you once again :)

**Comment by Buried-In-Code** [comment]
> Sorry to extend my requests, but I remember something that can be useful. Currently you exclude by type show or movie, what about adding excluding by library? Example, I have a library of Movies in German and I want those to stick to the German posters, but if I want to change the regular English posters there's no need to exclude the German movie library. Same for shows, if I want to keep the anime posters for example. Unless I miss something.
> 
> Thank you once again :)

Ive opened a new issue to track this #4

**Comment by DeuX01** [comment]
I have been thinking about this, would it be possible to pull from favorite users as it is now, but if no set from those users is available to a predetermined show, pull the most downloaded? instead of hardcode the list in the py maybe make it possible from the config file.

Thanks :)

**Comment by Buried-In-Code** [comment]
Ive been working on moving the users list to the config file, its currently on the dev branch while i test it. Its currently setup to only select a set from the list of users or if not users are configured then pull the first set (which should be the most downloaded).

It should be possible to add a flag or something to make it pull the first set if no user set was found.

**Comment by DeuX01** [comment]
Awesome! I’ll test it out tomorrow.
